version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: honeypot-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: honeypot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
